name: Doxygen

on:
  repository_dispatch:
  push:
    branches:
      - master
      - gh-pages

# In that case do the job 'make_and_deploy_doxygen'
jobs:
  job_check_doc_changes:
    runs-on: ubuntu-latest
    outputs:
      docs_changed: ${{ steps.check_doc_changes.outputs.nmydiffs }}
    steps:
      - name: Check doxygen inputs for changes
        uses: actions/checkout@v4
        with:
          # Checkout as many commits as needed for the diff
          fetch-depth: 2
      - name: Get diff and filter
        id: check_doc_changes
        run: |
          mydiffs=$(git diff --name-only HEAD^ HEAD)
          # Execute grep with || to avoud returning something != 0 and acctions getting an error
          nmydiffs=$(grep -c -e Readme.md -e c-container.h -e doxyfile.txt <<< ${mydiffs} || true)
          echo "nmydiffs=${nmydiffs}" | tee -a $GITHUB_OUTPUT

  make_and_deploy_doxygen:
    runs-on: ubuntu-latest
    needs: [ job_check_doc_changes ]
    if: needs.job_check_doc_changes.outputs.docs_changed != 0
    # which needs the following steps to be executed:
    steps:
      # 1. Checkout current branch of GitHub repository.
      - name: Checkout current branch
        uses: actions/checkout@v4
      # 2. Install doxygen and its auxiliary components.
      - name: Install doxygen
        run: sudo apt-get update; sudo apt-get install -y doxygen graphviz
      # 3. Create the doxygen pages.
      - name: Create the doxygen
        run: make Doxygen

      # Deploy to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: Doxygen
